### ISSUE TITLE
Handling exceptions in case configuration file data is not valid?

### ISSUE THREAD

**Issue by leonifrancopaz** [m3tro1d/pybackup#1]
In pybackup.py:
- Line 32 and Line 33: What if by mistake you use values that are not valid as you instructed them? It would be useful to handle that by having default values. I'm not fully sure how configparser and zipfile works yet, but since I found your script I will most likely use it to manage my own backups.

**Comment by m3tro1d** [comment]
Firstly, thanks for feedback! I'm glad that someone else beside me will use my little script.

As for the problem, I fixed it in [5932cd3](https://github.com/m3tro1d/pybackup/commit/5932cd3635714930cdbf071ee8332072e919021e). Now if the values are not numbers, it will terminate & inform about this. If the values are numbers out of range, it will fallback to the default `ZIP_DEFLATED` at level `5`.
